# Data Re-exploration of Common Weakness Enumeration (CWE)

* Name: Dohyeong Kwon (Ethan)
* Email: dkwon1@angelo.edu

In [1]:
from neo4j import GraphDatabase
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

uri = "bolt://localhost:7687"
username = "neo4j"
password = "abcd90909090"

driver = GraphDatabase.driver(uri, auth=(username, password))

def run_query(query, parameters=None):
    with driver.session() as session:
        result = session.run(query, parameters)
        return [record.data() for record in result]

In [2]:
# The number of UcoCWE nodes
query = """
MATCH (n:UcoCWE) RETURN count(n) AS UcoCWE
"""
params = {}

records = run_query(query, parameters=params)

df = pd.DataFrame(records)

df

   UcoCWE
0     968

In [3]:
# The properties of UcoCWE nodes
query = """
MATCH (n:UcoCWE)
UNWIND keys(n) AS key
RETURN DISTINCT key
"""
params = {}

records = run_query(query, parameters=params)

df = pd.DataFrame(records)

df

                         key
0              ucocweSummary
1     ucolikelihoodOfExploit
2             ucodescription
3       ucoalternative_terms
4      ucoapplicablePlatform
5      ucotimeOfIntroduction
6   ucodemonstrativeExamples
7    ucopotentialMitigations
8            ucomappingNotes
9        ucodetectionMethods
10            ucoabstraction
11     ucocommonConsequences
12    ucomodesOfIntroduction
13                  ucocweID
14                ucocweName
15                 ucostatus
16                       uri
17       ucoobservedExamples
18             ucoreferences
19              ucostructure
20  ucorelatedAttackPatterns
21     ucocweExtendedSummary

In [4]:
# The number of incoming relationships to UcoCWE nodes
query = """
MATCH (n:UcoCWE)<-[r]-(m)
RETURN DISTINCT type(r) AS incomingRelationship, count(r)
"""
params = {}

records = run_query(query, parameters=params)

df = pd.DataFrame(records)

df

      incomingRelationship  count(r)
0           UCOHASWEAKNESS       968
1  UCOEXHASRELATEDWEAKNESS      1212

In [5]:
# The number of outgoing relationships from UcoCWE nodes
query = """
MATCH (n:UcoCWE)-[r]->()
RETURN DISTINCT type(r) AS outgoingRelationship, count(r)
"""
params = {}

records = run_query(query, parameters=params)

df = pd.DataFrame(records)

df

    outgoingRelationship  count(r)
0  UCOHASOBSERVEDEXAMPLE      2999

In [6]:
# Node labels that are connected to UcoCWE nodes in a hop
query = """
MATCH (n:UcoCWE)-[r]-(m)
UNWIND labels(m) AS label
RETURN DISTINCT label AS targetNodeLabels
"""
params = {}

records = run_query(query, parameters=params)

df = pd.DataFrame(records)

df

       targetNodeLabels
0              Resource
1  UcoexObservedExample
2      UcoExploitTarget
3            UcoProduct
4                UcoTTP
5              UcoMeans
6            UcoexCAPEC

In [7]:
# The number of UcoExploitTarget nodes connected to UcoCWE nodes
# and the relationship type between them
query = """
MATCH (n:UcoCWE)<-[r]-(m:UcoExploitTarget)
RETURN DISTINCT count(m) AS numOfUcoExploitTarget, type(r) AS RelationshipType
"""
params = {}

records = run_query(query, parameters=params)

df = pd.DataFrame(records)

df

   numOfUcoExploitTarget RelationshipType
0                    968   UCOHASWEAKNESS

In [8]:
# The number of UcoexCAPEC nodes connected to UcoCWE nodes
# and the relationship type between them
query = """
MATCH (n:UcoCWE)<-[r]-(m:UcoexCAPEC)
RETURN DISTINCT count(m) AS numOfUcoexCAPEC, type(r) AS RelationshipType
"""
params = {}

records = run_query(query, parameters=params)

df = pd.DataFrame(records)

df

   numOfUcoexCAPEC         RelationshipType
0             1212  UCOEXHASRELATEDWEAKNESS

In [9]:
# The number of UcoexObservedExample(connected to UcoCVE) nodes connected to UcoCWE nodes
# and the relationship type between them
query = """
MATCH (n:UcoCWE)-[r]->(m:UcoexObservedExample)
RETURN DISTINCT count(m) AS numOfUcoexObservedExample, type(r) AS RelationshipType
"""
params = {}

records = run_query(query, parameters=params)

df = pd.DataFrame(records)

df

   numOfUcoexObservedExample       RelationshipType
0                       2999  UCOHASOBSERVEDEXAMPLE

In [ ]:
# The number of UcoCWE nodes and UcoexCPE nodes connected to each other in 3 hops
query = """
MATCH p = (n:UcoCWE)-[*1..3]-(m:UcoexCPE)
RETURN count(DISTINCT n) AS numOfCWE, count(DISTINCT m) AS numOfCPE
"""
params = {}

records = run_query(query, parameters=params)

df = pd.DataFrame(records)

df

   numOfCWE  numOfCPE
0       550      3058

In [13]:
# The number of UcoCWE nodes and UcoexCAPEC nodes connected to each other
query = """
MATCH p = (n:UcoCWE)-[r]-(m:UcoexCAPEC)
RETURN count(DISTINCT n) AS numOfCWE, count(DISTINCT m) AS numOfCAPEC
"""
params = {}

records = run_query(query, parameters=params)

df = pd.DataFrame(records)

df

   numOfCWE  numOfCAPEC
0       336         450